[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"


[project]
name = "resolver"
version = "0.1.0"
description = "A dig-like CLI for looking up DNS records"
requires-python = ">=3.11"  # tomllib

authors = [
    { name = "FMaged", email = "fadelmaged25@gmail.com" }
]

dependencies = [
    "dnspython>=2.7.0",
    "pydantic>=2.9",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
]

[project.scripts]
xdig = "resolver.main:main"


[tool.setuptools]
package-dir = { "" = "src" }
packages = ["resolver"]

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["E", "F", "W", "I"]

[tool.pytest.ini_options]
testpaths = ["tests"]
